Run mypy in CI.
mrc-ide/pyorderly pull request #30
Opened 2023-11-30 16:31 UTC by plietar

This required a couple of minor fixes here and there to get mypy to run without throwing errors.

2023-11-30 16:33 UTC, richfitz approved these changes
oh cool - I'll have to get you to show me how to exploit having types on things; it's not been super obvious how this interacts with the tooling.

2023-11-30 16:35 UTC, richfitz requested changes
ah, sorry - I see the ci is failing as ruff does not like relative imports. I am not at all tied to the current way of getting helper code into the tests, if you have a preferred way of doing this

2023-11-30 16:57 UTC, plietar commented
I think I have it working now.

- mypy couldn't resolve the `import helpers` statements, but it works if you make them relative instead.
- The relative `..helpers` import in `tests/orderly` only work if there's a `__init__.py` file around, but that was missing.
- Having that file around makes that directory importable, breaking all the `import orderly.current` statements that are actually looking for `src/orderly` due to the name collision.
- `tests/orderly` is only importable because `tests` gets added to the `sys.path` by the `pythonpath` option in `pyproject.toml`. Removing that line fixes it.

2023-12-04 11:05 UTC, richfitz approved these changes

2023-12-04 11:48 UTC, merged